before_install:
  - pip install --user codecov

jdk:
  - oraclejdk8
language: android
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-google-m2repository
    - extra-google-google_play_services
    - extra-android-m2repository

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories: #Cache all dirs under .gradle folder
    - $HOME/.gradle/daemon  #cache daemon logs
    - $HOME/.gradle/native  #cache library downloaded from gradle dependency
    - $HOME/.gradle/wrapper #cache gradle

script:
  - echo "branch is $TRAVIS_BRANCH"
  - echo "pull_request is $TRAVIS_PULL+REQUEST"
  - ls -a
  - cd resume_2017
  - echo "changed to application directory"
  - ls -a
  - echo "setting permissions on gradle wrapper"
  - chmod +x gradlew
  - echo "building"
  - ./gradlew build
  - echo "running unit tests"
  - ./gradlew test
  - echo "running lint"
  - ./gradlew lint
  # - echo "running instrumented checks"
  # - ./gradlew connectedCheck

after_success:
  - codecov